### ISSUE TITLE
Overview 리포 이름를 .github로 바꿀 것을 제안합니다.

### ISSUE THREAD

**Issue by rpopic2** [BRIDGE-DEV/.github#1]
리포 이름을`.github` 로 바꾸고 `/profile/README.md` 경로에 설명을 적으면 그룹 메인 페이지에 소개가 나오는 기능이 있습니다. 이 리포 이름을 `.github`로 바꿔도 좋을 것 같아요!

이름을 `.github-private`으로 하면 **멤버들이** 보는 메인 페이지에만 적용되니 `.github`와 `.github-private` 둘 다 만들어 놓으면 대외 소개용과 내부용으로 나누어서 사용할 수 있을 것 같아요.

첫 이슈가 저라니 부끄럽네요..(?)

p. s. Discussion 기능도 열어주시면 감사하겠습니다.. 혹은 권한을 주신다면 알아서 해보겠습니다...

**Comment by cedongne** [comment]
와 처음 알았네요. 바로 적용했습니다.

Discussion은 처음 조직 팠을 때 열었었는데 어느새 사라져 있었네요.. 일단 연 대상을 `.github`로 설정했는데, 권한 드릴테니 더 좋은 방식이 있다면 적용하고 이슈 등에 알려주시면 감사하겠습니다 :)

**Comment by rpopic2** [comment]
감사합니다!!
